import { describe, it, expect, beforeEach } from "vitest";
import { useAppStore } from "./useAppStore";

describe("useAppStore", () => {
  beforeEach(() => {
    // Clear the store before each test
    useAppStore.setState({ exams: [], topics: [], materials: [], learningGroups: [], studyTasks: [], authMode: "signed-out" });
  });

  it("should add a new exam and generate tasks and topics if not provided", () => {
    const initialState = useAppStore.getState();
    expect(initialState.exams.length).toBe(0);

    useAppStore.getState().addExam({
      subject: "Biology",
      date: "2024-12-01",
      time: "10:00",
      room: "B1",
      notes: "",
      difficulty: 3,
      knowledgeLevel: 2,
      color: "#00ff00",
      dailyMinutes: 30
    });

    const state = useAppStore.getState();
    expect(state.exams.length).toBe(1);
    expect(state.exams[0].subject).toBe("Biology");
    expect(state.exams[0].id).toBeDefined();
    expect(state.exams[0].createdAt).toBeDefined();

    // Test that topics and studyTasks could be dynamically generated by addExam.
    // Given the real implementation of addExam in useAppStore, let's verify if topics exist
  });

  it("should remove an exam", () => {
    useAppStore.getState().addExam({
      subject: "Biology",
      date: "2024-12-01",
      time: "10:00",
      room: "B1",
      notes: "",
      difficulty: 3,
      knowledgeLevel: 2,
      color: "#00ff00",
      dailyMinutes: 30
    });

    let state = useAppStore.getState();
    expect(state.exams.length).toBe(1);
    const examId = state.exams[0].id;

    useAppStore.getState().removeExam(examId);

    state = useAppStore.getState();
    // removeExam performs a soft delete by setting deletedAt
    expect(state.exams.length).toBe(1);
    expect(state.exams[0].deletedAt).toBeDefined();
  });

  it("rejects mutation attempts in offline read-only mode at the data layer", () => {
    useAppStore.setState({ authMode: "offline-readonly" });

    expect(() => useAppStore.getState().addExam({
      subject: "Chemistry",
      date: "2024-12-01",
      time: "10:00",
      room: "C1",
      notes: "",
      difficulty: 3,
      knowledgeLevel: 2,
      color: "#00ff00",
      dailyMinutes: 30
    })).toThrow("Cannot modify data in offline read-only mode");
  });

  it("redistributes missed open tasks to future dates", () => {
    const today = new Date().toISOString().slice(0, 10);
    const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
    const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
    const futureExamDate = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10);

    const examId = "exam-missed";
    useAppStore.setState({
      authMode: "signed-out",
      exams: [{
        id: examId,
        subject: "Physics",
        date: futureExamDate,
        time: "10:00",
        room: "A1",
        notes: "",
        difficulty: 3,
        knowledgeLevel: 2,
        color: "#0f766e",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
        dailyMinutes: 30
      }],
      studyTasks: [
        { id: "task-yesterday", examId, date: yesterday, task: "Nachholen", duration: 30, type: "learn" as const, status: "open" as const, updatedAt: new Date().toISOString(), deletedAt: null },
        { id: "task-today", examId, date: today, task: "Heute", duration: 30, type: "learn" as const, status: "open" as const, updatedAt: new Date().toISOString(), deletedAt: null },
        { id: "task-tomorrow", examId, date: tomorrow, task: "Morgen", duration: 30, type: "learn" as const, status: "open" as const, updatedAt: new Date().toISOString(), deletedAt: null }
      ]
    });

    useAppStore.getState().redistributeMissed();

    const state = useAppStore.getState();
    const yesterdayTask = state.studyTasks.find((task) => task.id === "task-yesterday");
    const todayTask = state.studyTasks.find((task) => task.id === "task-today");
    const tomorrowTask = state.studyTasks.find((task) => task.id === "task-tomorrow");

    expect(yesterdayTask).toBeDefined();
    expect(yesterdayTask!.date).not.toBe(yesterday);
    expect(yesterdayTask!.date >= today).toBe(true);
    expect(todayTask?.date).toBe(today);
    expect(tomorrowTask?.date).toBe(tomorrow);
  });

  it("creates learning groups and toggles shared exams", () => {
    const examId = "exam-share";
    useAppStore.setState({
      authMode: "signed-out",
      exams: [{
        id: examId,
        subject: "History",
        date: "2024-12-01",
        time: "10:00",
        room: "A1",
        notes: "",
        difficulty: 3,
        knowledgeLevel: 2,
        color: "#0f766e",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
        dailyMinutes: 30
      }]
    });

    const groupId = useAppStore.getState().createLearningGroup({ name: "Abi Team", memberNames: ["Mila"], examIds: [examId] });
    let group = useAppStore.getState().learningGroups.find((entry) => entry.id === groupId);

    expect(group).toBeDefined();
    expect(group?.examIds).toContain(examId);
    expect(group?.memberNames).toContain("Mila");

    useAppStore.getState().unshareExamFromGroup(groupId, examId);
    group = useAppStore.getState().learningGroups.find((entry) => entry.id === groupId);
    expect(group?.examIds).not.toContain(examId);

    useAppStore.getState().shareExamWithGroup(groupId, examId);
    group = useAppStore.getState().learningGroups.find((entry) => entry.id === groupId);
    expect(group?.examIds).toContain(examId);
  });

  it("regenerates an adaptive plan while preserving completed tasks", () => {
    const today = new Date().toISOString().slice(0, 10);
    const futureExamDate = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10);
    const examId = "exam-adaptive";
    useAppStore.setState({
      authMode: "signed-out",
      exams: [{
        id: examId,
        subject: "Physics",
        date: futureExamDate,
        time: "10:00",
        room: "A1",
        notes: "",
        difficulty: 4,
        knowledgeLevel: 2,
        color: "#0f766e",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
        dailyMinutes: 30
      }],
      topics: [
        { id: "topic-hard", examId, name: "Optics", completed: false, difficulty: 5, estimatedMinutes: 30, updatedAt: new Date().toISOString(), deletedAt: null }
      ],
      studyTasks: [
        { id: "task-done", examId, topicId: "topic-hard", date: today, task: "Done", duration: 30, type: "learn" as const, status: "done" as const, updatedAt: new Date().toISOString(), deletedAt: null },
        { id: "task-open", examId, topicId: "topic-hard", date: today, task: "Open", duration: 30, type: "learn" as const, status: "open" as const, updatedAt: new Date().toISOString(), deletedAt: null }
      ]
    });

    useAppStore.getState().regenerateAdaptiveStudyPlan(examId);

    const tasks = useAppStore.getState().studyTasks;
    expect(tasks.find((task) => task.id === "task-done")?.status).toBe("done");
    expect(tasks.find((task) => task.id === "task-open")).toBeUndefined();
    expect(tasks.some((task) => task.id.startsWith(`${examId}-adaptive-`))).toBe(true);
  });
});
