import { describe, it, expect, beforeEach } from "vitest";
import { useAppStore } from "./useAppStore";

describe("useAppStore", () => {
  beforeEach(() => {
    // Clear the store before each test
    useAppStore.setState({ exams: [], topics: [], materials: [], studyTasks: [], authMode: "signed-out" });
  });

  it("should add a new exam and generate tasks and topics if not provided", () => {
    const initialState = useAppStore.getState();
    expect(initialState.exams.length).toBe(0);

    useAppStore.getState().addExam({
      subject: "Biology",
      date: "2024-12-01",
      time: "10:00",
      room: "B1",
      notes: "",
      difficulty: 3,
      knowledgeLevel: 2,
      color: "#00ff00",
      dailyMinutes: 30
    });

    const state = useAppStore.getState();
    expect(state.exams.length).toBe(1);
    expect(state.exams[0].subject).toBe("Biology");
    expect(state.exams[0].id).toBeDefined();
    expect(state.exams[0].createdAt).toBeDefined();

    // Test that topics and studyTasks could be dynamically generated by addExam.
    // Given the real implementation of addExam in useAppStore, let's verify if topics exist
  });

  it("should remove an exam", () => {
    useAppStore.getState().addExam({
      subject: "Biology",
      date: "2024-12-01",
      time: "10:00",
      room: "B1",
      notes: "",
      difficulty: 3,
      knowledgeLevel: 2,
      color: "#00ff00",
      dailyMinutes: 30
    });

    let state = useAppStore.getState();
    expect(state.exams.length).toBe(1);
    const examId = state.exams[0].id;

    useAppStore.getState().removeExam(examId);

    state = useAppStore.getState();
    // removeExam performs a soft delete by setting deletedAt
    expect(state.exams.length).toBe(1);
    expect(state.exams[0].deletedAt).toBeDefined();
  });

  it("rejects mutation attempts in offline read-only mode at the data layer", () => {
    useAppStore.setState({ authMode: "offline-readonly" });

    expect(() => useAppStore.getState().addExam({
      subject: "Chemistry",
      date: "2024-12-01",
      time: "10:00",
      room: "C1",
      notes: "",
      difficulty: 3,
      knowledgeLevel: 2,
      color: "#00ff00",
      dailyMinutes: 30
    })).toThrow("Cannot modify data in offline read-only mode");
  });
});
